export const images = {
  basketball: "/basketball.jpg",
  football: "/football2.png",
  twoplayers: "/twoplayers.png",
  referee: "/referee.png",
  staf1: "/staf1.png",
  staf2: "/staf2.png",
  staf3: "/staf3.png",
  rewarding: "/rewarding.png",
  spectators: "/spectators.png",
  logo: "/logo.png",
  home: "/home.jpg",
  handball: "/handball.jpeg",
  rugby: "/rugby.jpeg",
  swimming: "/swimming.jpeg",
  athletics: "/athletics.jpeg",
  sponsor1: "/sponsor1.png",
  sponsor2: "/sponsor2.png",
  dot: "/dot.png",
  sports: "/sports.png",
  biglogo: "/biglogo.png",
  girls: "/girls.png",
  awarding: "/awarding.jpg",
  training: "/training.jpg",
  outreach: "/outreach.jpg",
  interscl: "/foot.png",
  running: "/running.png",
  baco: "/baco.png",
  rewarding2: "/rewarding.2.jpg",
  trophy: "/trophy.jpg",
  pp1: "/pp1.jpeg",
  pp2: "/pp2.jpeg",
  pp3: "/pp3.jpeg",
  pp4: "/pp4.jpeg",
  pp5: "/pp5.jpeg",
  riding:'/riding.jpeg',
  handbal:'/handbal.jpeg',
  athelets:'/athelets.jpeg',
  volley:"/volley.jpeg",
  foot:'/foot.jpeg',
  insipirations:'/insipirations.png',
  ins:'/ins.jpg'
};
